### PR TITLE
Replace kube-lego with cert-manager

### PR DESCRIPTION
**Pull request by miciek**
Related PR with the changes in the guide: https://github.com/hobby-kube/guide/pull/58

### CODE REVIEW

**Comment by pstadler** [comment]
Thanks for your contribution.

The "global" Certificate manifest for specifying domains is sub-optimal. Please make use of the [ingress-shim](https://cert-manager.readthedocs.io/en/latest/reference/ingress-shim.html) method instead (specifically the `kubernetes.io/tls-acme: "true"` part).
Besides that I'd like to run this within the `ingress` namespace.

**Comment by pstadler** [comment]
One more thing. Please use `.yml` instead of `.yaml` for the sake of consistency.

**Comment by miciek** [comment]
Thanks @pstadler for the tips :) Learned something new!

I did the changes you requested :) Please let me know what you think!

**Comment by pstadler** [comment]
Thank you. Tested it, works really well. 🍻

**Pull request merged**
